
import { Infraction, Natureza } from './types';

export const INITIAL_INFRACTIONS: Infraction[] = [
  {
    id: '751-01',
    artigo: '95',
    codigo_enquadramento: '751-01',
    titulo_curto: 'Iniciar obra perturbe/interrompa circulação/segurança s/permissão',
    descricao: 'Nenhuma obra ou evento que possa perturbar ou interromper a livre circulação de veículos e pedestres será iniciada sem permissão prévia.',
    natureza: Natureza.NAO_APLICAVEL,
    penalidade: 'Multa',
    pontos: 'Não computável',
    medidas_administrativas: [],
    quando_atuar: ['Responsável que iniciar obra que possa perturbar ou interromper a livre circulação sem permissão prévia.'],
    quando_nao_atuar: ['Quando houver permissão prévia e a obra ocorrer nos termos concedidos.', 'Se for evento, utilizar 751-02.'],
    exemplos_ait: ['Colocação de tapume sobre o passeio, prejudicando a circulação de pedestres, sem permissão.'],
    tags: ['obra', 'bloqueio', 'permissão', '95'],
    fonte_legal: 'CTB Art. 95',
    ultima_atualizacao: '2025-01-30',
    status: 'ativo'
  },
  {
    id: '501-00',
    artigo: '162, I',
    codigo_enquadramento: '501-00',
    titulo_curto: 'Dirigir veículo sem possuir CNH, PPD ou ACC',
    descricao: 'Dirigir veículo sem possuir Carteira Nacional de Habilitação, Permissão para Dirigir ou Autorização para Conduzir Ciclomotor.',
    natureza: Natureza.GRAVISSIMA,
    penalidade: 'Multa (3x)',
    pontos: 7,
    medidas_administrativas: ['Retenção do veículo até a apresentação de condutor habilitado'],
    quando_atuar: ['Condutor que não possui CNH, PPD ou ACC.', 'Condutor que não apresenta documento e sistema confirma que não é habilitado.'],
    quando_nao_atuar: ['Condutor com CNH cassada (usar 502-91).', 'Condutor com CNH vencida há mais de 30 dias (usar 504-50).'],
    exemplos_ait: ['Condutor não possui CNH ou PPD, conforme consulta aos sistemas.'],
    tags: ['habilitação', 'cnh', 'inabilitado', '162'],
    fonte_legal: 'CTB Art. 162, I',
    ultima_atualizacao: '2025-01-30',
    status: 'ativo'
  },
  {
    id: '516-91',
    artigo: '165',
    codigo_enquadramento: '516-91',
    titulo_curto: 'Dirigir sob a influência de álcool',
    descricao: 'Dirigir sob a influência de álcool ou de qualquer outra substância psicoativa que determine dependência.',
    natureza: Natureza.GRAVISSIMA,
    penalidade: 'Multa (10x) e suspensão do direito de dirigir por 12 meses',
    pontos: 7,
    medidas_administrativas: ['Recolhimento do documento de habilitação e retenção do veículo'],
    quando_atuar: ['Concentração de álcool >= 0,05 mg/L no etilômetro.', 'Condutor que apresentar dois ou mais sinais de alteração da capacidade psicomotora.'],
    quando_nao_atuar: ['Concentração <= 0,04 mg/L no etilômetro.'],
    exemplos_ait: ['Condutor realizou teste de etilômetro com resultado 0,20 mg/L.'],
    tags: ['álcool', 'embriaguez', 'lei seca', '165'],
    fonte_legal: 'CTB Art. 165',
    ultima_atualizacao: '2025-01-30',
    status: 'ativo'
  },
  {
    id: '518-51',
    artigo: '167',
    codigo_enquadramento: '518-51',
    titulo_curto: 'Deixar o condutor de usar o cinto de segurança',
    descricao: 'Deixar o condutor ou passageiro de usar o cinto de segurança, conforme previsto no art. 65.',
    natureza: Natureza.GRAVE,
    penalidade: 'Multa',
    pontos: 5,
    medidas_administrativas: ['Retenção do veículo até a colocação do cinto pelo infrator'],
    quando_atuar: ['Condutor que não estiver usando o cinto.', 'Cinto de 3 pontos usado de forma incorreta (sob o braço ou atrás do corpo).'],
    quando_nao_atuar: ['Veículos de transporte de passageiros em percursos onde é permitido viajar em pé.'],
    exemplos_ait: ['Condutor não usava cinto de segurança. A fivela estava em posição de repouso.'],
    tags: ['cinto', 'segurança', '167'],
    fonte_legal: 'CTB Art. 167',
    ultima_atualizacao: '2025-01-30',
    status: 'ativo'
  },
  {
    id: '545-21',
    artigo: '181, VIII',
    codigo_enquadramento: '545-21',
    titulo_curto: 'Estacionar no passeio',
    descricao: 'Estacionar o veículo no passeio ou sobre faixa destinada a pedestre, ciclovia, ilhas, refúgios, etc.',
    natureza: Natureza.GRAVE,
    penalidade: 'Multa',
    pontos: 5,
    medidas_administrativas: ['Remoção do veículo'],
    quando_atuar: ['Veículo estacionado em área destinada ao trânsito de pedestres, mesmo que apenas parte dele.'],
    quando_nao_atuar: ['Apenas parada para embarque/desembarque (usar enquadramento de parada).'],
    exemplos_ait: ['Veículo com uma das rodas sobre o passeio.'],
    tags: ['estacionamento', 'passeio', 'calçada', '181'],
    fonte_legal: 'CTB Art. 181, VIII',
    ultima_atualizacao: '2025-01-30',
    status: 'ativo'
  },
  {
    id: '550-90',
    artigo: '181, XIII',
    codigo_enquadramento: '550-90',
    titulo_curto: 'Estacionar no ponto de embarque/desembarque de transporte coletivo',
    descricao: 'Estacionar o veículo onde houver sinalização delimitadora de ponto de transporte coletivo ou a menos de 10m do marco.',
    natureza: Natureza.MEDIA,
    penalidade: 'Multa',
    pontos: 4,
    medidas_administrativas: ['Remoção do veículo'],
    quando_atuar: ['Estacionado na área delimitada pela pintura amarela.', 'Na ausência de pintura, a menos de 10 metros antes ou depois do marco do ponto.'],
    quando_nao_atuar: ['Ônibus de linha regular no ponto final.'],
    exemplos_ait: ['Veículo estacionado junto ao marco do ponto de ônibus.'],
    tags: ['estacionamento', 'ônibus', 'transporte coletivo', '181'],
    fonte_legal: 'CTB Art. 181, XIII',
    ultima_atualizacao: '2025-01-30',
    status: 'ativo'
  },
  {
    id: '747-10',
    artigo: '218, III',
    codigo_enquadramento: '747-10',
    titulo_curto: 'Transitar em velocidade superior à máxima em mais de 50%',
    descricao: 'Transitar em velocidade superior à máxima permitida para o local em mais de 50%.',
    natureza: Natureza.GRAVISSIMA,
    penalidade: 'Multa (3x) e suspensão imediata do direito de dirigir',
    pontos: 7,
    medidas_administrativas: [],
    quando_atuar: ['Velocidade medida superior ao limite regulamentado acrescido de 50%.'],
    quando_nao_atuar: ['Velocidade inferior a 50% acima do limite (usar 745-50 ou 746-30).'],
    exemplos_ait: ['Veículo flagrado a 120km/h em via de 60km/h.'],
    tags: ['velocidade', 'excesso', 'radar', '218'],
    fonte_legal: 'CTB Art. 218, III',
    ultima_atualizacao: '2025-01-30',
    status: 'ativo'
  },
  {
    id: '605-01',
    artigo: '208',
    codigo_enquadramento: '605-01',
    titulo_curto: 'Avançar o sinal vermelho do semáforo',
    descricao: 'Avançar o sinal vermelho do semáforo ou o de parada obrigatória.',
    natureza: Natureza.GRAVISSIMA,
    penalidade: 'Multa',
    pontos: 7,
    medidas_administrativas: [],
    quando_atuar: ['Semáforo efetivamente no vermelho no início da passagem pela linha de retenção.'],
    quando_nao_atuar: ['Conversão à direita permitida por sinalização específica mesmo no vermelho.'],
    exemplos_ait: ['Condutor avançou o sinal vermelho e seguiu em frente.'],
    tags: ['semáforo', 'sinal vermelho', '208'],
    fonte_legal: 'CTB Art. 208',
    ultima_atualizacao: '2025-01-30',
    status: 'ativo'
  },
  {
    id: '763-31',
    artigo: '252, parágrafo único',
    codigo_enquadramento: '763-31',
    titulo_curto: 'Dirigir veículo segurando telefone celular',
    descricao: 'Dirigir veículo segurando ou manuseando telefone celular.',
    natureza: Natureza.GRAVISSIMA,
    penalidade: 'Multa',
    pontos: 7,
    medidas_administrativas: [],
    quando_atuar: ['Condutor com o aparelho na mão, mesmo que não esteja em ligação (ex: lendo mensagem).'],
    quando_nao_atuar: ['Celular em suporte no painel sendo usado apenas para GPS sem manuseio.'],
    exemplos_ait: ['Condutor dirigia segurando o celular com a mão direita próxima ao volante.'],
    tags: ['celular', 'telefone', 'distração', '252'],
    fonte_legal: 'CTB Art. 252, P.U.',
    ultima_atualizacao: '2025-01-30',
    status: 'ativo'
  },
  {
    id: '527-41',
    artigo: '175',
    codigo_enquadramento: '527-41',
    titulo_curto: 'Utilizar veículo para demonstrar manobra perigosa mediante arrancada brusca',
    descricao: 'Utilizar-se de veículo para demonstrar ou exibir manobra perigosa, mediante arrancada brusca, derrapagem ou frenagem.',
    natureza: Natureza.GRAVISSIMA,
    penalidade: 'Multa (10x), suspensão do direito de dirigir e apreensão do veículo',
    pontos: 7,
    medidas_administrativas: ['Recolhimento do documento de habilitação e remoção do veículo'],
    quando_atuar: ['Condutor que utiliza o veículo com o propósito de se exibir, realizando arrancada brusca ("queimar pneu").'],
    quando_nao_atuar: ['Manobra feita para evitar acidente (situação de emergência).'],
    exemplos_ait: ['Condutor arrancou bruscamente após o sinal verde, fazendo os pneus deslizarem e emitirem ruído.'],
    tags: ['manobra', 'perigo', 'exibição', '175'],
    fonte_legal: 'CTB Art. 175',
    ultima_atualizacao: '2025-01-30',
    status: 'ativo'
  }
];
